### ISSUE TITLE
About arxiv paper image

### ISSUE THREAD

**Issue by kei97103** [Ha0Tang/LGGAN#1]
Hello. I saw your paper at arxiv.
https://arxiv.org/pdf/1912.12215.pdf

And I have a question.
In Fig. 1, Fig. 16, Fig. 17, Global & Global+Local image are very similar.

If Local affects the Global+Local, it is thought that Local pixel in the white area of ​​Local weight should appear in the result, but there is no such tendency. Am I misunderstanding?

**Comment by Ha0Tang** [comment]
1. the difference between `Global` and `Global+Local` is subtle, we suggest you visualize the difference
2. the local weight is much weaker than the global weight, so the effect of the local branch is not very obvious
3. the `Global` and `Local` brancher are complementary, and the local branch aims to enhance the edge between different objects
