### ISSUE TITLE
When can you make the code public?

### ISSUE THREAD

**Issue by KevinMarkVine** [Ha0Tang/LGGAN#2]
I have read your article and I want to reproduce your work

**Comment by Ha0Tang** [comment]
Thanks for your interest in our work. I will release the code in two weeks.

**Comment by jinx2018** [comment]
> Thanks for your interest in our work. I will release the code in two weeks.

Two months has passed, could you release the code ?

**Comment by Ha0Tang** [comment]
Hi, will definitely release the code this week.

**Comment by IwenLeeO** [comment]
hello, 12 days has passed , could you release the code ?  interest in you work  , thanks.

**Comment by Ha0Tang** [comment]
@KevinMarkVine @jinx2018 @IwenLeeO Hi, everything is uploaded, please let me know if you have any questions?
