### ISSUE TITLE
Link to pretrained models for Semantic Image Synthesis are broken

### ISSUE THREAD

**Issue by TiagoCortinhal** [Ha0Tang/LGGAN#6]
Hey!

Thank you for make the source code available. 
The links for the pretrained models are broken. Can you fix this? 
Thanks!
```
disi.unitn.it/~hao.tang/uploads/models/LGGAN/cityscapes_pretrained.tar.gz
disi.unitn.it/~hao.tang/uploads/models/LGGAN/ade_pretrained.tar.gz
```

**Comment by Ha0Tang** [comment]
Hi, please try this `sh scripts/download_lggan_model.sh LGGAN_[dataset]`
